pipeline {
    agent any
    stages {
        stage('for any branch') {
            steps {
                checkout scmGit(branches: [[name: '*/**']], extensions: [], userRemoteConfigs: [[credentialsId: 'd6b99116-2f2d-47b9-9a25-d935a47dcbbf', url: 'https://bitbucket.org/provility-admin/recommendation-system.git']])
            }
        }
        pipeline {
            agent any
            stages {
                stage('Trigger Branch Jobs') {
                    steps {
                        script {
                            def branchName = env.BRANCH_NAME

                            switch(branchName) {
                                case 'main':
                                    echo "Triggering main branch job"
                                    build job: 'main-branch-job'
                                    break
                                case 'develop':
                                    echo "Triggering develop branch job"
                                    build job: 'develop-branch-job'
                                    break
                                case 'qa':
                                    echo "Triggering qa branch job"
                                    build job: 'qa-branch-job'
                                    break
                                case 'staging':
                                    echo "Triggering staging branch job"
                                    build job: 'staging-branch-job'
                                    break
                                default:
                                    echo "No matching branch job found"
                            }
                        }
                    }
                }
            }
        }
}
}
